repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.1
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
  - id: mypy
