[tool.mypy]
disable_error_code = ["import-untyped"]

[tool.ruff]
exclude = [
  ".git",
  "user-config.py",
  ".venv",
]

[tool.ruff.lint]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
